### PR TITLE
bump ahash

### PR DESCRIPTION
**Pull request by nuke-web3**
Build fails for me otherwise with feature missing issue

### CODE REVIEW

**Comment by Slesarew** [comment]
This is a very bad manner of fixing things; it's an upstream issue that's lodged inside of hazmat cryptographical dependencies so it certainly should not be fixed within lock file bypassing the . The proper manner of fixing it *for now* is presented in #25 while permanent fix is getting rid of major garbage deps sp-core blob maintained in insustainable manner being worked on in #26 (it's ready on its own, but NFC packets format changes in anticipation of metadata-merklization update, so we are waiting for Siltti update being ready before shipping that into production). Yet, I suppose this solution could be used by developers jumping in, so I'll keep this open like I keep #25 open until we merge #26.

**Comment by NukeManDan** [comment]
> cryptographical dependencies

yes - I  should have known not to touch _internals_ of those things 🤦 - thanks for the explanation here. I might be the only person to run into this if #26 is going in before any more DIY kits are used. Otherwise I would suggest updating any learning materials to point to using that branch. If you do intend to enable others to DIY build kits & compile this repo, I would suggest merging the fix for now and when ready for the right fix, revert the change & rebase the final solution. UX will be better and it will prevent others for attempting my flawed solution.

**Comment by nuke-web3** [comment]
was this resolved now? I still have the hardware I would love to build & flash... have not tried since opening this PR

**Comment by Slesarew** [comment]
Yes, with latest merge it was! (by ditching Substrate deps in favor of lighter and cleaner ones)

**Pull request closed without merging**
